console.log()

console.log(typeof("str"))
console.log(typeof(123))
console.log(typeof(Infinity))
console.log(typeof(NaN))
console.log(typeof(10n))
console.log(typeof(true))
console.log(typeof(Symbol))
console.log(typeof([]))
console.log(typeof({}))
console.log(typeof(Function()))
console.log(typeof(undefined))
console.log(typeof(null))

console.log(13 > 18 ? true : false, "1")
console.log(`${1 + 2}`, "2")
console.log(6 - '2', "3")
console.log(~2, "4")
console.log(String.fromCodePoint(90), "5")
console.log('abc'.localeCompare('abc'), "6")
console.log(`Hello`.at(-2), "7")
console.log('abc'.indexOf('b'), "8")
console.log('abc'.includes('c'), "9")
console.log('abc'.startsWith('ab'), "10")
console.log('abc'.endsWith('bc'), "11")
console.log('abcde'.slice(0,3), "12")
console.log('abcde'.slice(2), "13")
console.log('z'.codePointAt(0), "14")
console.log('1,2,3'.split(', '), "15")

console.log(1e3)
console.log(1e-6)
console.log(0xff)
console.log(0b11111111)
console.log(0o377)
console.log(Number('123'))
console.log(1.23456.toFixed(2))
console.log(new Number(0))
console.log(isNaN(NaN))
console.log(isFinite("15"))
console.log(parseInt('100px'))
console.log(parseFloat('12.5em'))
console.log(Math.max(3,5,1))

console.log(0 == [])
console.log(['a',1,`eee`][2])
console.log(['a',1,{name: 'Max'},`eee`][2].name)
console.log(['a',1,{name: 'Max'},`eee`].at(-2))
console.log(['a',1, ,`eee`].length)
console.log(['a','b','c'].pop())
console.log(['a','b','c'].shift())
console.log(['a','b','c'].push('d'))
console.log(['a','b','c'].unshift('d'))
console.log(new Array('a','b'))
console.log(['a','b','c'].splice(1,1))
console.log(['a','b','c'].splice(2,0,'d','e'))
console.log([1,2].concat([3]))
console.log([1,2,3].forEach(a=>console.log((a))))
console.log([1,2,3].indexOf(2))
console.log([1,2,3].lastIndexOf(3))
console.log([1,2].includes(2))
console.log([1,2,3,4].map((a,acc)=> acc = a+ a))
console.log([1,2,15].sort())
console.log([1,2,15].sort(a=> Number(a)))
console.log([1,2,3].reverse())
console.log([1,2,3].join(','))
console.log([1,2,3,4].reduce((a,acc)=>acc+a))

console.log(undefined ?? "Аноним")
console.log(null ?? "S" ?? "X")
console.log(0 || 100)
console.log(0 ?? 100)




