print('a')
print("a")
print('''a''')
print(str(98.6))
print('a'+'b')
print('a'*4)
print('ab'[0])
print('abc'[:])
print('abc'[1:])
print('abc'[-2:])
print('abc'[::2])
print('abcdefj'[::2])
print(len('abc'))
print(''.join(['a','b']))
print(','.join(['a','b']))
print('ab'.replace('a','c'))
print(' abc ')
print(' abc '.strip())
print('a'.startswith('a'))
print('a'.endswith('a'))
print('a'.center(3))
print('a'.ljust(2))
print('a'.rjust(2))
